### ISSUE TITLE
Question on the posterior likelihood for (alpha,beta |y )

### ISSUE THREAD

**Issue by arcolombo** [paulnorthrop/bang#1]
The posterior of alpha, beta i can derive to match the equation listed here (https://cran.r-project.org/web/packages/bang/vignettes/bang-b-hef-vignette.html)

the equation pi(a,b) i don't think corresponds to this equation described in the function 'gamma_pois_marginal_loglik '

could you clarify which likelihood is the gamma_pois_marginal_loglik' corresponding to ?  (p(a,b | y) ?

if i derive the hyperparameter posterior on my end, the log like is in this form, which i'm not sure which likelihood is in this function
thanks for clarifying

```
 LP<-0
  for(i in 1:length(y)){
  LP <-LP+lgamma(a+y[i])+a*log(b) -lgamma(a)-(a+y[i])*log(b+x[i])
  }
```

**Comment by paulnorthrop** [comment]
In the code, x is the vector (alpha, beta), y is the vector (y1, ..., yJ) and off is the vector (e1, ..., eJ). The term involving log(beta + ej) has been manipulated to log(1 + ej/beta) + log(beta) and the second of these terms cancel with an earlier term. Otherwise, I think that the only difference between our codes is that mine is vectorised and yours is not.
